version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: doctor_db
      POSTGRES_PASSWORD: doctor1234
      POSTGRES_DB: doctor_db
    ports:
      - "4001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres_data: